Reports.Web/Controllers/EditionsController.cs
using System;
using System.Web.Mvc;
using CommonService;
using Legendary.Core.Utils;
using Reports.Application.Models;
using Reports.Client;
using Reports.Models;

namespace Reports.Application.Controllers
{
    public class EditionsController : BaseLoggedController
    {
        private readonly GeneralReportServices _generalReportServices;

        public EditionsController()
        {
            _generalReportServices = new GeneralReportServices(SiteParameter.Get("reports.api").Get<string>());
        }

        public JsonResult SaveResponseEmailed(ViewModels.EmailResponse emailResponse)
        {
            var done = false;
            if (!ModelState.IsValid)
            {
                done = false;
            }

            var report = _generalReportServices.GetReport(emailResponse.ReportId);
            if (report.IsNotEmptyOrNull())
            {
                done = true;
                var todayDate = new DateTime();
                todayDate = TimeZoneInfo.ConvertTimeToUtc(DateTime.Now, TimeZoneInfo.Local);
                var edition = new Edition();
                edition.ReportId = emailResponse.ReportId;
                edition.UTCDateEdited = todayDate;
                edition.EditedById = UserService.LoginManager.GetLoggedUser().userId;
                edition.Content = "Email de respuesta enviado : " + emailResponse.Body;

                _generalReportServices.CreateEdition(edition);

                report.Status = (int) Enums.ReportsStatus.InFollowing;
                report.ModifiedByUserId = UserService.LoginManager.GetLoggedUser().userId;
                report.UtcDateModified = todayDate;
                _generalReportServices.UpdateReport(report);
            }

            return new JsonResult() { JsonRequestBehavior = JsonRequestBehavior.AllowGet, Data = new { saved = done } };
        }

        public ActionResult Create(int reportId)
        {
            var edition = new Edition { ReportId = reportId };
            return View(edition);
        }

        [HttpPost]
        public ActionResult Create(Edition edition)
        {
            // "Central Standard Time (Mexico)"
            var todayDate = TimeZoneInfo.ConvertTimeToUtc(DateTime.Now, TimeZoneInfo.Local);
            edition.UTCDateEdited = todayDate;
            edition.EditedById = UserService.LoginManager.GetLoggedUser().userId;

            if (!ModelState.IsValid)
                return View(edition);

            var report = _generalReportServices.GetReport(edition.ReportId);
            if (report.IsEmptyOrNull())
                return RedirectToAction("Index", "Reports");
            if (report.Status != (int)Enums.ReportsStatus.Closed)
            {
                report.ModifiedByUserId = edition.EditedById;
                report.Status = (int)Enums.ReportsStatus.InFollowing;
                try
                {
                    _generalReportServices.UpdateReport(report);
                    _generalReportServices.CreateEdition(edition);

                }
                catch (Exception)
                {
                    return RedirectToAction("Index", "Reports");
                }                
            }

            return RedirectToAction("Details", "Reports", new { reportId = edition.ReportId });
        }

        public ActionResult Close(int reportId)
        {
            var edition = new Edition { ReportId = reportId };
            return View(edition);
        }

        [HttpPost]
        public ActionResult Close(Edition edition)
        {
            // "Central Standard Time (Mexico)"
            var todayDate = new DateTime();
            todayDate = TimeZoneInfo.ConvertTimeToUtc(DateTime.Now, TimeZoneInfo.Local);
            edition.UTCDateEdited = todayDate;
            edition.EditedById = UserService.LoginManager.GetLoggedUser().userId;


            if (!ModelState.IsValid)
                return View(edition);

            var report = _generalReportServices.GetReport(edition.ReportId);
            if (report.IsEmptyOrNull())
                return RedirectToAction("Index", "Reports");
            if (report.Status != (int)Enums.ReportsStatus.Closed)
            {
                report.ModifiedByUserId = edition.EditedById;
                report.Status = (int)Enums.ReportsStatus.Closed;
                report.Priority = (int)Enums.ReportPriority.Low;
                try
                {
                    _generalReportServices.UpdateReport(report);
                    _generalReportServices.CreateEdition(edition);

                }
                catch (Exception)
                {
                    return RedirectToAction("Index", "Reports");
                }
            }

            return RedirectToAction("Details", "Reports", new { reportId = edition.ReportId });
        }
        [HttpPost]
        public ActionResult changePriority(int reportId, int Priority)
        {
            String PriorityText = string.Empty;
            switch (Priority)
            {
                case 0:
                    PriorityText = "Urgente";
                    break;
                case 1:
                    PriorityText = "Baja";
                    break;
                case 2:
                    PriorityText = "Regular";
                    break;
                case 3:
                    PriorityText = "Baja";
                    break;                    
            }
            var edition = new Edition { ReportId = reportId };
            var todayDate = new DateTime();
            todayDate = TimeZoneInfo.ConvertTimeToUtc(DateTime.Now, TimeZoneInfo.Local);
            edition.UTCDateEdited = todayDate;
            edition.EditedById = UserService.LoginManager.GetLoggedUser().userId;


            if (!ModelState.IsValid)
                return View(edition);

            var report = _generalReportServices.GetReport(reportId);
            if (report.IsEmptyOrNull())
                return RedirectToAction("Index", "Reports");
            if (report.Status != (int)Enums.ReportsStatus.Closed)
            {
                report.ModifiedByUserId = edition.EditedById;
                report.Priority = Priority;
                report.UtcDateModified = todayDate;
                edition.Content = "Prioridad del reporte actualizada a " + PriorityText;
                try
                {
                    _generalReportServices.UpdateReport(report);
                    _generalReportServices.CreateEdition(edition);

                }
                catch (Exception)
                {
                    return RedirectToAction("Index", "Reports");
                }
            }
            return RedirectToAction("Details", "Reports", new { reportId = edition.ReportId });
        }
       
    }
}

Reports.Web/Controllers/InvolvedTypesController.cs
using System.Web.Mvc;
using CommonService;
using Reports.Client;
using Reports.Models;

namespace Reports.Application.Controllers
{
    public class InvolvedTypesController : Controller
    {
        private readonly GeneralReportServices _generalReportServices;

        public InvolvedTypesController()
        {
            _generalReportServices = new GeneralReportServices(SiteParameter.Get("reports.api").Get<string>());
        }

        // GET: InvolvedTypes
        public ActionResult Index()
        {
            var involvedTypesList = _generalReportServices.GetInvolvedTypes();
            return View(involvedTypesList);
        }

        public ActionResult Create()
        {
           return View();            
        }

        [HttpPost]
        public ActionResult Create(InvolvedType involvedType)
        {
            if (!ModelState.IsValid)
                return View(involvedType);

            _generalReportServices.CreateInvolvedType(involvedType);
            return RedirectToAction("Index");
        }

    }
}

Reports.Web/Views/Shared/_Layout.cshtml
@using UserService;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vigia Ciudadano(Reportes y Sugerencias)</title>
    @Styles.Render("~/Content/css")
    <link href="~/Content/custom.css" rel="stylesheet">
    <link href="/Content/style-desktop.css" rel="stylesheet">
    <link href="/Content/style.css" rel="stylesheet">
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <link href="/Content/enjoyhint.css" rel="stylesheet">    
    @RenderSection("head", required: false)
    @*<script type="text/javascript">
        var appInsights=window.appInsights||function(config){
            function s(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},r=document,f=window,e="script",o=r.createElement(e),i,u;for(o.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",r.getElementsByTagName(e)[0].parentNode.appendChild(o),t.cookie=r.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)s("track"+i.pop());return config.disableExceptionTracking||(i="onerror",s("_"+i),u=f[i],f[i]=function(config,r,f,e,o){var s=u&&u(config,r,f,e,o);return s!==!0&&t["_"+i](config,r,f,e,o),s}),t
        }({
            instrumentationKey:"f5b7d71e-d497-40d7-a137-59fd92a25698"
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>*@
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

</head>
<body>
    <div class="mainContainer">
        <nav class="navbar navbar-main" id="topBar">
            <div class="container">
                <div class="navbar-header">
                    @if (LoginManager.IsLoggedIn())
                    {
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    }
                    @Html.ActionLink("Vigia Ciudadano", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    @if (LoginManager.IsLoggedIn())
                    {
                        var currentUser = LoginManager.GetLoggedUser();
                        var messageSources = SecurityService.Manager.HasPermissions(LoginManager.GetLoggedUser().userId, (int)SecurityService.Model.SystemPermissions.ReportsPermissions.CreateMessageSource);
                        var reportTypes = SecurityService.Manager.HasPermissions(LoginManager.GetLoggedUser().userId, (int)SecurityService.Model.SystemPermissions.ReportsPermissions.CreateReportType);
                        var involvedTypes = SecurityService.Manager.HasPermissions(LoginManager.GetLoggedUser().userId, (int)SecurityService.Model.SystemPermissions.ReportsPermissions.CreateInvolvedType);
                        var statistics = SecurityService.Manager.HasPermissions(LoginManager.GetLoggedUser().userId, (int)SecurityService.Model.SystemPermissions.ReportsPermissions.ViewStatistics);
                        <p class="navbar-text navbar-right navbar-user"><!--<span class="icon icon-user"></span>--></p>
                        <ul class="nav nav-main">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Reportes <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>@Html.ActionLink("Ver Todos", "Index", "Reports", new { }, null)</li>
                                    <li class="divider"></li>
                                    <li><a href="#">Asignados a mi</a></li>
                                    <li><a href="#">Abiertos por mi</a></li>
                                    <li><a href="#">Pendientes de mi area</a></li>
                                    <li class="divider"></li>
                                    <li>@Html.ActionLink("Crear nuevo reporte", "Create", "Reports")</li>
                                </ul>
                            </li>
                            @if (statistics)
                            {
                                <li>@Html.ActionLink("Estadísticas", "ReportStatistics", "Reports", new { }, null)</li>}
                            <li class="dropdown">
                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Catalogos<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    @if (messageSources)
                                    {
                                        <li>@Html.ActionLink("Fuentes de Origen", "Index", "MessageSources")</li>}
                                    @if (reportTypes)
                                    {
                                        <li>@Html.ActionLink("Tipos de Reporte", "Index", "ReportTypes")</li>}
                                    @if (involvedTypes)
                                    {
                                        <li>@Html.ActionLink("Tipos de involucrados", "Index", "InvolvedTypes")</li>}
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">@currentUser.firstName @currentUser.lastName <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>
                                        @Html.ActionLink("Cerrar sesión", "Logout", "Account")
                                    </li>
                                    <li>
                                        <a href="#" id="useHelp">Ayuda</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
        <div class="container body-content contentGeneral" id="centerDiv" style="height:85%;">
            @RenderBody()
            <hr />
        </div>
        <footer class="footerbottom contenedor-pie">
            <div style="width:55px; margin: 0 auto; margin-bottom: -2px;">
                <img src="/../Content/treegreen.png" />
            </div>
            <div style="width: 100%; height: 7px; background: #007848;"></div>
        </footer>
    </div>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        <script src="/Scripts/enjoyhint.js"></script>  
         
        @RenderSection("scripts", required: false)
    <script type="text/javascript">
    $(document).ready(bodyResize);
    $(window).resize(bodyResize);
    $("#useHelp").click(function () {
        enjoyhint_instance.run();
    });
    function bodyResize() {

    }
    </script>
    
    <script>

    $(function() {

        $('#InvolvedTypeId').change(function () {
        $('.person-fields').hide();
        $('.' + $(this).val()).show();
    });

    $("#new_comment").focusin(function() {
      $("#new_comment_btn").show();
    });

    $("[data-toggle=popover]").popover({
        html : true,
        placement : 'auto bottom',
        trigger : 'focus',
        content: function() {
          var content = $(this).attr("data-popover-content");
          return $(content).html();
        }
    });

    });
    </script>
    <script type="text/javascript">
    $(document).ready(function () {
        $('#submitBtn').click(function () {
            SendMail();
        });

    });
    function SendMail() {
        $('#load').show();
        $.ajax
  		(
			{
			    type: "POST",
			    url: "https://tribalancemailsender.azurewebsites.net/api/email",
			    dataType: 'json',
			    crossDomain: true,
			    data: $("#formToSerialize").serialize(),
			    success: function () {
			        alert('Mensaje enviado, por favor espere se esta por redireccionar la pagina.');
			        $.ajax({
			            type: "POST",
			            url: "@Url.Action("SaveResponseEmail","Editions")",
			            data: $("#formToSerialize").serialize()
			        });
			        window.location.replace("/home");
			        $('#load').hide();
			    },
			    error: function (e) {
			        var errorMessage = "";
			        if (e.responseJSON.ModelState["email.Body"] != undefined) {
			            errorMessage += e.responseJSON.ModelState["email.Body"] + ' . ';
			        }
			        if (e.responseJSON.ModelState["email.AddressFrom"] != undefined) {
			            errorMessage += e.responseJSON.ModelState["email.AddressFrom"];
			        }
			        $('#load').hide();
			        alert(errorMessage);
			    },
			    headers: {
			        "Authorization": "Basic L1ei4U4DzESM77aFqwxJjo6J8lGMDPXaF37y0xsv7tQP2c+dtbyl9hhwi654GA+n/z+39wUeir4/Kb+d+alJgNDcBlq4UaHrdvNVVXOQ2zg="
			    }
			}
		);
    }
    </script>
</body>
</html>

Reports.Web/Views/Shared/_LayoutPageWithOutMenu.cshtml
@using UserService;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Vigia Ciudadano(Reportes y Sugerencias)</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

    @Styles.Render("~/Content/font")
    <link href="/Content/style-desktop.css" rel="stylesheet">
    <link href="/Content/style.css" rel="stylesheet">
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <link href="/Content/enjoyhint.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="~/Content/printCondition.css" media="print" />
    @RenderSection("head", required: false)
    @*<script type="text/javascript">
            var appInsights=window.appInsights||function(config){
                function s(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},r=document,f=window,e="script",o=r.createElement(e),i,u;for(o.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",r.getElementsByTagName(e)[0].parentNode.appendChild(o),t.cookie=r.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)s("track"+i.pop());return config.disableExceptionTracking||(i="onerror",s("_"+i),u=f[i],f[i]=function(config,r,f,e,o){var s=u&&u(config,r,f,e,o);return s!==!0&&t["_"+i](config,r,f,e,o),s}),t
            }({
                instrumentationKey:"f5b7d71e-d497-40d7-a137-59fd92a25698"
            });

            window.appInsights=appInsights;
            appInsights.trackPageView();
        </script>*@
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

</head>
<body>
        @RenderBody()
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="/Scripts/enjoyhint.js"></script>

    @RenderSection("scripts", required: false)

    <script>

    $(function() {

        $('#InvolvedTypeId').change(function () {
        $('.person-fields').hide();
        $('.' + $(this).val()).show();
    });

    $("#new_comment").focusin(function() {
      $("#new_comment_btn").show();
    });

    $("[data-toggle=popover]").popover({
        html : true,
        placement : 'auto bottom',
        trigger : 'focus',
        content: function() {
          var content = $(this).attr("data-popover-content");
          return $(content).html();
        }
    });

    });
    </script>
    <script type="text/javascript">
    $(document).ready(function () {
        $('#submitBtn').click(function () {
            SendMail();
        });

    });
    function SendMail() {
        $('#load').show();
        $.ajax
  		(
			{
			    type: "POST",
			    url: "https://tribalancemailsender.azurewebsites.net/api/email",
			    dataType: 'json',
			    crossDomain: true,
			    data: $("#formToSerialize").serialize(),
			    success: function () {
			        alert('Mensaje enviado, por favor espere se esta por redireccionar la pagina.');
			        $.ajax({
			            type: "POST",
			            url: "@Url.Action("SaveResponseEmail","Editions")",
			            data: $("#formToSerialize").serialize()
			        });
			        window.location.replace("/home");
			        $('#load').hide();
			    },
			    error: function (e) {
			        var errorMessage = "";
			        if (e.responseJSON.ModelState["email.Body"] != undefined) {
			            errorMessage += e.responseJSON.ModelState["email.Body"] + ' . ';
			        }
			        if (e.responseJSON.ModelState["email.AddressFrom"] != undefined) {
			            errorMessage += e.responseJSON.ModelState["email.AddressFrom"];
			        }
			        $('#load').hide();
			        alert(errorMessage);
			    },
			    headers: {
			        "Authorization": "Basic L1ei4U4DzESM77aFqwxJjo6J8lGMDPXaF37y0xsv7tQP2c+dtbyl9hhwi654GA+n/z+39wUeir4/Kb+d+alJgNDcBlq4UaHrdvNVVXOQ2zg="
			    }
			}
		);
    }
    </script>
</body>
</html>